### ISSUE TITLE
Help find ayat v2 not working

### ISSUE THREAD

**Issue by muhammadalkady** [quran/ayah-detection#10]
As-salamu alaykum
I have tried `ayat.py` and it is working, but `find_ayat_v2.py` which is used by main.py is not working or detecting any markers.
`ayat.py` is using a template marker. How `find_ayat_v2.py` is working?. It has no template marker parameter.
This is one of the pages that I am working with.
![3](https://user-images.githubusercontent.com/44714079/147867952-f32608c8-764a-4875-8549-886c846f4a75.jpg)

**Comment by ahmedre** [comment]
wa3laikum alsalam,
per the documentation:

> find_ayat_v2.py is a simpler version of ayat.py that uses OpenCV to find contours instead. consequently, this script doesn't need a template image. the downside of this approach, however, is that it can have many false positives since certain letters can still be detected as contours. this can greatly be reduced if the ayah markers have colors, which most do - simply checking for colors in a certain range greatly reduces (if not completely eliminates) these false positives. this is the recommended approach moving forward in sha' Allah.

in other words, v2 looks for circles with colors inside it to denote ayah markers and therefore doesn't need a template. to use v2, you'd need to tweak the color values it searches for inside of the script. otherwise, try with v1.

**Comment by muhammadalkady** [comment]
Thanks this helped me so much.
I have generated the database successfully. 
جزاك الله خيرا
