### ISSUE TITLE
generate metadata for quran.com-images generated image 

### ISSUE THREAD

**Issue by alaeddinegallas** [quran/ayah-detection#2]
Salamou alaykom,

This is not an issue just a question !

first of all thank you for opening the source for the tools you have done for the application. I really appreciate the fact you are sharing this knowledge with the community. Baraka Allahou fikom.

I want to port Quran Android to iOS (iPhone & iPad)  (with your permission) and I want to share this project with the community as well.
I just started the seed of the project and hopefully when It reach certain point of maturity I will share the project with you and will open it for the community.

I'am in a R&D stage of the project. So far I was able to generate the image using the scripts you have shared (https://github.com/quran/quran.com-images) . Those scripts only generate the images but doesn't output any metadata ( location of each ayah and lines and coordinate inside the image). Will this scripts help me generate those meta data ? Or do you have any ready to use data for the base text you are using (madani for now but I think this script is made for qaloon and warsh scans ) ?  The metadata need to be adapted to higher resolution (specially for retina display resolution ) 

Thank you !

**Comment by sharabash** [comment]
@ahmedre?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
sure, it'd be great if you work on an iOS port, and if you want to develop it in the open, several people have pinged me asking to contribute on such a project if one exists, so can put them in touch if so insha'Allah.

quran/quran.com-images does output the location of every verse (and i believe every word in every verse as well). i can't remember off the top of my head if it writes a sqlite database directly, or instead writes to a mysql database, and there's a script to export that into sqlite or something. if you'd like, you can start directly by pulling one of our predefined sizes that we provide with quran for android - ex [1920 images](http://android.quran.com/data/images_1920.zip).

but yes, this project is more for images that aren't generated by us (detecting the ayah symbols in a ready quran image), so for madani support, quran.com-images is what you want.

please let me know if you have more questions!
walsalam 3alaikum.

**Comment by alaeddinegallas** [comment]
salamou alaykom brother Ahmed,

Thank you for taking time to answer my question. ( and sorry for the delay of my response)

I searched the generate.qurna.page.pl script for any code that output sql statement but I didn't find any. But this is not a problem. This project (ayah-detection) is doing a good job for detecting the lines, the starting and the ending of every ayah but is not suited for the first and second page ( Al-Fatiha and the second and first 6 ayah of Al-Baqarah )

I can reuse the pre generated data you already have, but its seems that is more for Android devices. What I want is having for every iDevice type a double set of image ( for both portrait and landscape ). Every device will have to download the set of image as well as ayah bound data depending on it's own width/hight.
Thats why those scripts are of great help for me. But if any of those perl script is already doing the job that will be great. 

Yes indeed I will open the project so everyone who want to help is welcome. So far I'am focusing on the main functionalities ( navigation, ayah interaction and highlighting ). As soon as this is ready I will let you know and send you a test version and we will decide the next step :) 

Two last questions :
The nice rectangle around every ayah name is a manual work right ? Can you share any resource for that ?
Can I send any email if I'am in need ? ( ah...re@gmail.com )

Thank you brother !

**Comment by ahmedre** [comment]
wa3laikum alsalam,
there are 2 branches - i believe the nextgen branch is the one that outputs sql. the device isn't specific in any way to Android devices - it all depends on the sizes you need for the images - if one of the pre-made sizes works for you, you can use it for iOS just fine, since iOS supports sqlite.

there are other ppl interested in working on an iOS version, so can you start a github repo so i can point people who are interested to work with you and help you out?

do you mean the rectangle around the sura name? it's part of the QCF_BSML.ttf font that is in the repo. sure, feel free to email me.

walsalam 3alaikum.
