### ISSUE TITLE
main.py not working..

### ISSUE THREAD

**Issue by farazhaider88** [quran/ayah-detection#3]
how do you run these scripts... 

i tried following steps but getting this issue while executing main.py 👍 

Traceback (most recent call last):
  File "main.py", line 121, in <module>
    if end_of_sura:
NameError: name 'end_of_sura' is not defined

i run first ayat.py and get res.png

then i run lines.py and test.png with 5 lines in surah fatihah while it should be 6 0r 7 if we include bismillah too.

but i cannot work out how to run main.py ..

please help

Jazakallah

**Comment by dajdouj10** [comment]
please help me, how run these scripts

**Comment by ahmedre** [comment]
really sorry for the late reply - i haven't looked at this repo in a long time, but have started to again recently. closing for now, please re-open if you still are having issues and will be happy to help in sha' Allah.
