### ISSUE TITLE
Need instruction on find_lines function

### ISSUE THREAD

**Issue by ahsanaasim** [quran/ayah-detection#4]
Assalamu Alaikum, 

I am trying to generate metadata for Quran images. But for getting lines, I am confused about the parameters I need to pass. Can you please tell me how do i calculated max pixels and mode?

**Documentation says:**

there are 3 numbers you'll find configured in the main - line height (approximate height of each line), max pixels **(a threshold - how many pixels in a line make the line a quran line vs a line of tashkeel between two lines)**, and mode (**0 or 1 - i think this is used for how to handle the very first line - pass 0 for most cases)**.

If you could explain with an image, that would be appreciated. Better if you could explain using the following image. Thanks

![006](https://user-images.githubusercontent.com/17532073/52911678-3b8a8c00-32d1-11e9-9b67-99ed440ac686.jpg)

**Comment by ahmedre** [comment]
wa3laikum alsalam,
sorry for the delayed reply. setting those values goes in the `__main__` - but i don't think this image will work with the script due to the borders (which there is no support for yet).
walsalam 3alaikum.

**Comment by ahmedre** [comment]
kind of late but i just had to deal with a case like this - [mogrify](https://www.imagemagick.org/script/mogrify.php), which is part of imagemagick - is your friend for removing these borders - sample usage:

```sh
mogrify -crop 1352x2170+356+282 page003.png
```

in this case, we are saying "i want an output image that's 1352x2170" - "start that image from position 356x282" - by computing the values of this for your page you can get the image without borders in sha' Allah.

please reopen if you still need help with this.
jazakumAllah khairan.
