### ISSUE TITLE
Aya marker using custom icon!

### ISSUE THREAD

**Issue by AhmedAsser** [quran/ayah-detection#7]
Salamo alykom,
Is there a version of Madinah Mushaf pages available without aya marker like the image below, Including SQL data that represent aya mark location on every line?
![110467005-26af0a00-80df-11eb-8b44-cd755df737cf](https://user-images.githubusercontent.com/5795325/111278389-257f5f00-8642-11eb-8507-189de0e1409a.png)
Does "ayah-detection repo" remove aya marker from images and create marker SQL data for marker positions?
Thanks.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
yes, this repo has tools to remove the ayah markers from images like this and to record their positions.
walsalam 3alaikum
