### ISSUE TITLE
Order of the Chapters are incorrect in the select menu 

### ISSUE THREAD

**Issue by ZiyadF296** [quran/ayah-detection#9]
I have realized that the Chapters (Suar') in the top left menu is not correctly ordered.
I recommend checking the index in the Quran just to be sure.

**Comment by ahmedre** [comment]
this script is for detecting the location of ayah markers in images and therefore i am not sure what you are referring to.

walsalam 3alaikum.

**Comment by ZiyadF296** [comment]
Sure, it was a mistake, I have posted this same issue in another and appropriate repository.
Sorry for the inconvenience.
